import * as vscode from 'vscode';
import { spawnSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

export type MutagenStatus =
  | { kind: 'not_installed' }
  | { kind: 'connecting' }
  | { kind: 'watching' }
  | { kind: 'syncing'; transferring?: number }
  | { kind: 'conflict'; files: string[] }
  | { kind: 'paused' }
  | { kind: 'error'; message: string }
  | { kind: 'no_session' };

export interface MutagenTarget {
  project: string;
  host: string;
  user: string;
  sshPort?: number;
  localPath: string;
  remotePath: string;
}

const IGNORE_PATTERNS = [
  // Common build / dependency directories
  'node_modules',
  '.next',
  'dist',
  'build',
  '.dart_tool',
  'ios/Pods',
  // Lock files we don't care about syncing live
  '.DS_Store',
  // Our own scratch
  '.remote-claude',
  '.devbridge',
];

const POLL_INTERVAL_MS = 2000;

/**
 * Wraps the `mutagen` CLI for a bidirectional sync session between the laptop
 * and the Mac Mini. Replaces the old rsync-based one-way SyncController.
 *
 * Lifecycle:
 *   ensureInstalled() → ensureSession() → status events → terminate()
 *
 * On conflict, "alpha wins" — our --mode is `two-way-resolved` and the laptop
 * is alpha. The Mini's losing version is preserved with a `.conflict-N`
 * suffix in the same directory so nothing is permanently lost.
 */
export class MutagenController {
  private statusEmitter = new vscode.EventEmitter<MutagenStatus>();
  readonly onStatusChange = this.statusEmitter.event;
  private last: MutagenStatus = { kind: 'no_session' };
  private timer?: NodeJS.Timeout;
  private terminated = false;

  constructor(
    private readonly target: MutagenTarget,
    private readonly output: vscode.OutputChannel,
  ) {}

  /**
   * Stable session name. Mutagen names must match `[a-z0-9](-?[a-z0-9])*` —
   * lowercase alphanumeric with single dashes. No underscores, dots,
   * uppercase, or consecutive dashes allowed.
   */
  private get sessionName(): string {
    const raw = `rc-${this.target.project}-${this.target.host}`.toLowerCase();
    return raw
      .replace(/[^a-z0-9-]/g, '-')   // anything else → dash
      .replace(/-+/g, '-')           // collapse consecutive dashes
      .replace(/^-+|-+$/g, '');      // trim leading/trailing dashes
  }

  /**
   * Write a small shell wrapper that injects our per-project SSH key into
   * every ssh invocation mutagen makes. Returns its absolute path. Idempotent
   * — overwriting an existing wrapper is safe and keeps it in sync if the
   * key path or port changes.
   */
  private ensureSshWrapper(): string {
    const dir = join(homedir(), '.remote-claude', 'ssh-wrappers');
    mkdirSync(dir, { recursive: true });
    const wrapperPath = join(dir, `${this.target.host}-${this.target.user}.sh`);
    const keyPath = join(homedir(), '.remote-claude', 'keys', `${this.target.host}-${this.target.user}`);
    const portFlag = this.target.sshPort && this.target.sshPort !== 22 ? `-p ${this.target.sshPort} ` : '';
    const keyFlag = existsSync(keyPath) ? `-i '${keyPath}' ` : '';
    const script =
      `#!/bin/sh\n` +
      `# Auto-generated by Remote Claude — injects per-project SSH config into mutagen's transport.\n` +
      `exec ssh ${keyFlag}${portFlag}-o StrictHostKeyChecking=accept-new -o BatchMode=yes "$@"\n`;
    writeFileSync(wrapperPath, script, 'utf8');
    chmodSync(wrapperPath, 0o755);
    return wrapperPath;
  }

  /** True if `mutagen` is on PATH. */
  static isInstalled(): boolean {
    const r = spawnSync('mutagen', ['version'], { encoding: 'utf8', timeout: 5000 });
    return r.status === 0;
  }

  /** True if a session with our name currently exists in the mutagen daemon. */
  private sessionExists(): boolean {
    const r = spawnSync('mutagen', ['sync', 'list', this.sessionName, '--template', '{{ .Name }}'], {
      encoding: 'utf8',
      timeout: 10000,
    });
    return r.status === 0 && r.stdout.trim() === this.sessionName;
  }

  /** Create the bidirectional sync session if it doesn't exist yet. */
  async ensureSession(): Promise<{ ok: true } | { ok: false; error: string }> {
    if (!MutagenController.isInstalled()) {
      this.emit({ kind: 'not_installed' });
      return { ok: false, error: 'mutagen not installed' };
    }

    if (this.sessionExists()) {
      this.output.appendLine(`[mutagen] session "${this.sessionName}" already running, reattaching`);
      this.startPolling();
      return { ok: true };
    }

    this.emit({ kind: 'connecting' });

    const wrapperPath = this.ensureSshWrapper();
    const beta = `${this.target.user}@${this.target.host}:${this.target.remotePath}`;
    const args = [
      'sync', 'create',
      '--name', this.sessionName,
      '--mode', 'two-way-resolved',          // alpha (laptop) wins conflicts
      '--symlink-mode', 'posix-raw',         // preserve symlinks as-is
      '--ignore-vcs',                        // skip .git/, .hg/, etc.
      ...IGNORE_PATTERNS.flatMap((p) => ['--ignore', p]),
      '--default-file-mode', '0644',
      '--default-directory-mode', '0755',
      this.target.localPath,
      beta,
    ];
    // MUTAGEN_SSH_PATH lets us override the ssh binary mutagen invokes. We
    // point it at a small wrapper that injects -i <per-project-key> + -p
    // <sshPort>, then execs the real ssh. Without this, mutagen would use
    // ~/.ssh/id_* (which our setup never installs on the Mini) and the
    // transport would fail with permission denied.
    const env = { ...process.env, MUTAGEN_SSH_PATH: wrapperPath };

    this.output.appendLine(`[mutagen] creating session "${this.sessionName}" → ${beta}`);
    const r = spawnSync('mutagen', args, { encoding: 'utf8', timeout: 60000, env });
    if (r.status !== 0) {
      const err = (r.stderr || r.stdout || `exit ${r.status}`).trim();
      this.output.appendLine(`[mutagen] create failed: ${err}`);
      this.emit({ kind: 'error', message: err });
      return { ok: false, error: err };
    }
    this.output.appendLine(`[mutagen] session created`);
    this.startPolling();
    return { ok: true };
  }

  /** Force an immediate sync flush. Returns when the flush completes. */
  /** Env for every mutagen invocation — ensures our SSH wrapper is in place. */
  private mutagenEnv(): NodeJS.ProcessEnv {
    return { ...process.env, MUTAGEN_SSH_PATH: this.ensureSshWrapper() };
  }

  async flush(): Promise<void> {
    spawnSync('mutagen', ['sync', 'flush', this.sessionName], { encoding: 'utf8', timeout: 60000, env: this.mutagenEnv() });
    this.poll();
  }

  pause(): void {
    spawnSync('mutagen', ['sync', 'pause', this.sessionName], { encoding: 'utf8', timeout: 10000, env: this.mutagenEnv() });
    this.poll();
  }

  resume(): void {
    spawnSync('mutagen', ['sync', 'resume', this.sessionName], { encoding: 'utf8', timeout: 10000, env: this.mutagenEnv() });
    this.poll();
  }

  /** Terminate the session and stop polling. Called on extension deactivation. */
  async terminate(): Promise<void> {
    this.terminated = true;
    if (this.timer) clearInterval(this.timer);
    spawnSync('mutagen', ['sync', 'terminate', this.sessionName], { encoding: 'utf8', timeout: 10000, env: this.mutagenEnv() });
    this.statusEmitter.dispose();
  }

  /** Current cached status (last poll). */
  status(): MutagenStatus {
    return this.last;
  }

  private startPolling(): void {
    if (this.timer) return;
    this.poll();
    this.timer = setInterval(() => this.poll(), POLL_INTERVAL_MS);
  }

  /**
   * Parse `mutagen sync list <name>` long output and derive a MutagenStatus.
   * We use a template that captures the fields we care about so parsing is
   * stable across mutagen versions.
   */
  private poll(): void {
    if (this.terminated) return;
    // Template: status word + paused flag + conflict count + first few conflict paths
    const tpl = `{{ .Status }}|{{ .Paused }}|{{ len .Conflicts }}|{{ range .Conflicts }}{{ .AlphaChanges }}{{ "\\t" }}{{ end }}`;
    const r = spawnSync('mutagen', ['sync', 'list', this.sessionName, '--template', tpl], {
      encoding: 'utf8',
      timeout: 10000,
    });
    if (r.status !== 0) {
      // Session might have been terminated externally; report no_session
      this.emit({ kind: 'no_session' });
      return;
    }
    const out = r.stdout.trim();
    const parts = out.split('|');
    const statusWord = parts[0] ?? '';
    const paused = (parts[1] ?? '').toLowerCase() === 'true';
    const conflictCount = Number(parts[2] ?? '0');

    if (paused) {
      this.emit({ kind: 'paused' });
      return;
    }
    if (conflictCount > 0) {
      // Get conflict file paths via a more specific template
      const cr = spawnSync(
        'mutagen',
        ['sync', 'list', this.sessionName, '--long'],
        { encoding: 'utf8', timeout: 10000, env: this.mutagenEnv() },
      );
      const files = extractConflictPaths(cr.stdout || '');
      this.emit({ kind: 'conflict', files: files.slice(0, 10) });
      return;
    }
    // Status word values seen: "Watching", "Scanning", "Staging files...", "Connecting",
    // "Waiting for rescan", "Reconciling", "Ready"
    const s = statusWord.toLowerCase();
    if (s.includes('watching') || s.includes('ready') || s === '') {
      this.emit({ kind: 'watching' });
    } else if (s.includes('connect')) {
      this.emit({ kind: 'connecting' });
    } else {
      // Anything else (scanning, staging, reconciling) → syncing
      this.emit({ kind: 'syncing' });
    }
  }

  private emit(s: MutagenStatus): void {
    // Coalesce identical consecutive statuses
    if (statusEq(s, this.last)) return;
    this.last = s;
    this.statusEmitter.fire(s);
  }
}

function statusEq(a: MutagenStatus, b: MutagenStatus): boolean {
  if (a.kind !== b.kind) return false;
  if (a.kind === 'conflict' && b.kind === 'conflict') {
    return a.files.join('') === b.files.join('');
  }
  if (a.kind === 'error' && b.kind === 'error') {
    return a.message === b.message;
  }
  return true;
}

/**
 * Pull conflicting file paths out of `mutagen sync list --long` output.
 * The long output includes a Conflicts section listing them; we grep for
 * lines that look like file paths. Best-effort — if mutagen's output
 * format drifts, we just return an empty list and the UI shows count only.
 */
function extractConflictPaths(longOut: string): string[] {
  const lines = longOut.split('\n');
  const out: string[] = [];
  let inConflicts = false;
  for (const line of lines) {
    if (/^Conflicts:/i.test(line.trim())) {
      inConflicts = true;
      continue;
    }
    if (inConflicts) {
      if (!line.trim()) {
        inConflicts = false;
        continue;
      }
      const m = line.match(/(?:α|β)\s*\(([^)]+)\)/) || line.match(/^\s*[α|β]?\s*"?([^"\s][^"\n]+)"?\s*$/);
      if (m && m[1]) out.push(m[1]);
    }
  }
  return out;
}
